// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN2sUZAJ9a-uremYrtnbPFvqXxkkWsEKI',
    appId: '1:287047561003:web:32a59c0ae241235acb5f6e',
    messagingSenderId: '287047561003',
    projectId: 'estehjumbo-8a538',
    authDomain: 'estehjumbo-8a538.firebaseapp.com',
    storageBucket: 'estehjumbo-8a538.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF0FKcewcRw-RmATl2fnWGMzQbmu21fO8',
    appId: '1:287047561003:android:ea80dc1594682055cb5f6e',
    messagingSenderId: '287047561003',
    projectId: 'estehjumbo-8a538',
    storageBucket: 'estehjumbo-8a538.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAisJ7Ma457fpX955HDTDYmA5wY5psIiA',
    appId: '1:287047561003:ios:3f7d5f7a5087c12ccb5f6e',
    messagingSenderId: '287047561003',
    projectId: 'estehjumbo-8a538',
    storageBucket: 'estehjumbo-8a538.appspot.com',
    iosBundleId: 'com.example.tehjumbofirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAisJ7Ma457fpX955HDTDYmA5wY5psIiA',
    appId: '1:287047561003:ios:3f7d5f7a5087c12ccb5f6e',
    messagingSenderId: '287047561003',
    projectId: 'estehjumbo-8a538',
    storageBucket: 'estehjumbo-8a538.appspot.com',
    iosBundleId: 'com.example.tehjumbofirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN2sUZAJ9a-uremYrtnbPFvqXxkkWsEKI',
    appId: '1:287047561003:web:4a1cbd7d1a2d57c3cb5f6e',
    messagingSenderId: '287047561003',
    projectId: 'estehjumbo-8a538',
    authDomain: 'estehjumbo-8a538.firebaseapp.com',
    storageBucket: 'estehjumbo-8a538.appspot.com',
  );
}
